name: projet_satisfaction_client
services:
  etl_elt:
    container_name: satisfaction_client_etl_elt
    build: ./etl_elt/.
    environment:
      - POSTGRES_SRV_ADDRESS=${postgres_srv_address}
      - POSTGRES_SRV_PORT=${postgres_srv_port}
      - POSTGRES_DB=${postgres_srv_database}
      - POSTGRES_USER=${postgres_srv_user}
      - POSTGRES_PASSWORD=${postgres_srv_password}
    volumes:
      - ./etl_elt/scripts:/app/scripts
      - ./volumes/etl_elt:/app/extracts
    command: python /app/scripts/etl_elt.py
    depends_on:
      postgresql_db:
        condition: service_healthy

  postgresql_db:
    container_name: pg_container
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${postgres_srv_user}
      POSTGRES_PASSWORD: ${postgres_srv_password}
      POSTGRES_DB: ${postgres_srv_database}
    ports:
      - "${postgres_srv_port}:${postgres_srv_port}"
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${postgres_srv_user} -d ${postgres_srv_database}"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s